// Copyright (c) 2026 Athan Clark. SPDX-License-Identifier: GPL-3.0-only
// Deterministic benchmark timelines: the same size and seed always produce the same document.
import { Q, validateDocument } from '../dist/core.mjs';

export const DEFAULT_SIZES = [1000, 10000, 100000, 200000];
const TAGS = ['war', 'trade', 'science', 'art', 'religion', 'politics', 'migration', 'climate'];
const WORDS =
  'harbor treaty river council market census eclipse harvest siege charter voyage archive'.split(
    ' ',
  );

/** mulberry32: a small, fast, seedable PRNG. */
function prng(seed) {
  return () => {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
/** Coordinates span 0 to 10^9 (about 32 years of seconds) with exact 1/8 fractions. */
export const SPAN = 1_000_000_000;
/**
 * A realistic mix: two thirds of moments fall in dense clusters (with coincident times), the
 * rest spread uniformly. One duration per ten moments (a third anchored to moments, most short,
 * some long), one relationship per ten moments, and tags on about half of the entities.
 */
export function generateTimeline(size, seed = 27) {
  const random = prng(seed + size);
  const pick = (list) => list[Math.floor(random() * list.length)];
  const clusters = Array.from({ length: Math.max(1, Math.floor(size / 500)) }, () =>
    Math.floor(random() * SPAN),
  );
  const tags = () => TAGS.filter(() => random() < 0.12);
  const events = [];
  // A timeline holds at most 200,000 moments; leave room for the create benchmark.
  const count = Math.min(size, 199999);
  for (let i = 0; i < count; i++) {
    const base =
      random() < 2 / 3
        ? pick(clusters) + Math.floor((random() - 0.5) * 200000)
        : Math.floor(random() * SPAN);
    const t = tags();
    events.push({
      id: 'm' + i,
      time: Q.from(BigInt(base) * 8n + BigInt(Math.floor(random() * 8)), 8n).toString(),
      metadata: {
        title: `${pick(WORDS)} ${pick(WORDS)} ${i}`,
        description: `Notes about the ${pick(WORDS)} near the ${pick(WORDS)} (${i}).`,
        ...(t.length ? { tags: t } : {}),
      },
    });
  }
  const durations = [];
  for (let i = 0; i < Math.floor(size / 10); i++) {
    const start = Math.floor(random() * SPAN);
    const length = random() < 0.8 ? Math.floor(random() * 100000) : Math.floor(random() * 50000000);
    const t = tags();
    durations.push({
      id: 'd' + i,
      start:
        random() < 1 / 3 ? { moment: 'm' + Math.floor(random() * count) } : String(start) + '/1',
      end: String(start + length) + '/1',
      metadata: { title: `${pick(WORDS)} period ${i}`, ...(t.length ? { tags: t } : {}) },
    });
  }
  const relationships = [];
  for (let i = 0; i < Math.floor(size / 10); i++) {
    const a = { moment: 'm' + Math.floor(random() * count) };
    const b =
      random() < 0.8
        ? { moment: 'm' + Math.floor(random() * count) }
        : { duration: 'd' + Math.floor(random() * Math.max(1, durations.length)) };
    if (JSON.stringify(a) !== JSON.stringify(b) && durations.length) relationships.push({ a, b });
  }
  return validateDocument({
    format: 'openchronology',
    version: 1,
    title: `Benchmark timeline (${size} moments)`,
    description: 'Generated by bench/generate.mjs for latency benchmarks.',
    events,
    durations,
    relationships,
  });
}
/** Inputs shared by every backend so operations are comparable. */
export function workload(document) {
  const times = document.events.map((e) => Q.parse(e.time)).sort((a, b) => a.compare(b));
  const first = times[0],
    last = times.at(-1),
    span = last.sub(first);
  const middle = first.add(span.div(Q.from(2n)));
  const zoom = span.div(Q.from(100n));
  const target = document.events[Math.floor(document.events.length / 2)];
  return {
    full: { lower: first.toString(), upper: last.toString() },
    zoomed: {
      lower: middle.sub(zoom.div(Q.from(2n))).toString(),
      upper: middle.add(zoom.div(Q.from(2n))).toString(),
    },
    width: 1000,
    pixels: 24,
    target,
    page: { lower: middle.toString(), upper: last.toString(), limit: 100 },
  };
}
